server :
  port : 8081

spring :
  datasource :
    driver-class-name : org.mariadb.jdbc.Driver
    url : jdbc:mariadb://localhost:3306/test_db
    username : root
    password : root

  jpa :
    hibernate : create
    properties :
      hibernate :
        format_sql : true
    show-sql : true